### ISSUE TITLE
Cannot build without CouchDB specified in config

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#103]
When CouchDB is not specified in config file (which is default) the
`npm run build -- -env.configFileLocation=configuration.properties` command throws an error:
```
Using configuration:  configuration.properties
C:\Tools\dcat-ap-viewer\node_modules\webpack-cli\bin\cli.js:244
                                throw err;
                                ^

TypeError: Cannot read property 'length' of null
    at getRepositoryType (C:\Tools\dcat-ap-viewer\configuration.js:67:42)
    at initialize (C:\Tools\dcat-ap-viewer\configuration.js:21:27)
    at Object.<anonymous> (C:\Tools\dcat-ap-viewer\configuration.js:32:3)
    at Module._compile (C:\Tools\dcat-ap-viewer\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (C:\Tools\dcat-ap-viewer\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Tools\dcat-ap-viewer\build\webpack.common.js:4:16)
    at Module._compile (C:\Tools\dcat-ap-viewer\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (C:\Tools\dcat-ap-viewer\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Tools\dcat-ap-viewer\build\webpack.production.js:9:34)
    at Module._compile (C:\Tools\dcat-ap-viewer\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (C:\Tools\dcat-ap-viewer\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (C:\Tools\dcat-ap-viewer\node_modules\webpack-cli\bin\convert-argv.js:133:13)
    at requireConfig (C:\Tools\dcat-ap-viewer\node_modules\webpack-cli\bin\convert-argv.js:135:6)
    at C:\Tools\dcat-ap-viewer\node_modules\webpack-cli\bin\convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Tools\dcat-ap-viewer\node_modules\webpack-cli\bin\convert-argv.js:140:15)
    at yargs.parse (C:\Tools\dcat-ap-viewer\node_modules\webpack-cli\bin\cli.js:241:39)
    at Object.parse (C:\Tools\dcat-ap-viewer\node_modules\yargs\yargs.js:552:18)
    at C:\Tools\dcat-ap-viewer\node_modules\webpack-cli\bin\cli.js:219:8
    at Object.<anonymous> (C:\Tools\dcat-ap-viewer\node_modules\webpack-cli\bin\cli.js:530:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dcat-viewer@1.0.0-alpha.0 build: `cross-env NODE_ENV=production webpack --config build/webpack.production.js "-env.configFileLocation=configuration.properties"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dcat-viewer@1.0.0-alpha.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kuba\AppData\Roaming\npm-cache\_logs\2018-10-05T08_14_50_533Z-debug.log
```

Since CouchDB is optional, this should not happen.

**Comment by jakubklimek** [comment]
Still happening in d3e13117731405e58371ef34bab5eee6dd3d330c
